// Hooks
#define HANDLE_INPUT						0xCB067C4
#define CLIENT_INSTANCE_UPDATE				0x6402998
#define LEVEL_RENDERER_PLAYER_GET_FOV		0x76798A8
#define CONTAINER_SCREEN_CONTROLLER_TICK	0x5D36EE4

// Methods
#define ACTOR_COLLISION_IS_ON_GROUND						0xAB8E924
#define ACTOR_GET_ARMOR										0xAE4DF44
#define ACTOR_GET_DIMENSION									0xAE41348
#define ACTOR_GET_ENTITY_TYPE_ID							0xAE3DB58
#define ACTOR_GET_OFFHAND_SLOT								0xAE4E578
#define ACTOR_GET_RUNTIME_ID								0xAE3E530
#define ACTOR_GET_UNIQUE_ID									0xAE3E76C
#define ACTOR_SET_POS										0xAE42540
#define ACTOR_TRY_GET_FROM_ENTITY							0xAE64E48
#define ACTOR__INITIALIZE_MAX_AUTO_STEP						0xAE5D594 /* Actor::setStepHeight */
#define ARMOR_ITEM_GET_SLOT_FOR_ITEM						0xB9507DC /* ItemStackBase::getArmorSlot was removed by the optimizer because why not */
#define CLIENT_INSTANCE_GET_MOVE_TURN_INPUT					0x691DC94
#define CONTAINER_SCREEN_CONTROLLER__GET_ITEM_STACK			0x5D3A0A4
#define CONTAINER_SCREEN_CONTROLLER__HANDLE_AUTO_PLACE		0x5D38438
#define ITEM_STACK_BASE_GET_AUX_VALUE						0xB948D5C
#define ITEM_STACK_BASE_IS_NULL								0xB94F3CC
#define ITEM_STACK_BASE_IS_WEARABLE_ITEM					0xB954A08
#define MINECRAFT_PACKETS_CREATE_PACKET						0x920B308
#define PLAYER_INVENTORY_GET_ITEM							0xAB7A08C
#define PLAYER_INVENTORY_GET_SELECTED_ITEM					0xAB7A330
#define PLAYER_INVENTORY_GET_SELECTED_SLOT					0xAB7A2BC
#define PLAYER_INVENTORY_SELECT_SLOT						0xAB7A2D8
#define PLAYER_TRY_GET_FROM_ENTITY							0xAB6C074
#define STACK_RESULT_STORAGE_ENTITY_CONSTRUCTOR				0xDA062D4
#define STACK_RESULT_STORAGE_ENTITY__GET_STACK_REF			0xDA064D8
#define STACK_RESULT_STORAGE_ENTITY__HAS_VALUE				0xDA064D0
#define SYNCHED_ACTOR_DATA_ENTITY_WRAPPER_GET_STATUS_FLAG	0xAB9BB54
#define SYNCHED_ACTOR_DATA_ENTITY_WRAPPER_GET_STRING		0xB1D866C
#define SYNCHED_ACTOR_DATA_ENTITY_WRAPPER_SET_STATUS_FLAG	0xAB9BC3C

// Vtable indices
#define ACTOR_IS_INVISIBLE_VT							33
#define ACTOR_GET_CARRIED_ITEM_VT						82
#define BLOCK_SOURCE_GET_BLOCK_VT						3
#define CLIENT_INSTANCE_GET_LEVEL_VT					189
#define CLIENT_INSTANCE_GET_LOCAL_PLAYER_VT				31
#define CLIENT_INSTANCE_GET_TOP_SCREEN_NAME_VT			150
#define GAME_MODE_ATTACK_VT								15
#define GAME_MODE_BUILD_BLOCK_VT						7
#define GAME_MODE_CONTINUE_BUILD_BLOCK_VT				8
#define GAME_MODE_START_BUILD_BLOCK_VT					6
#define GAME_MODE_STOP_BUILD_BLOCK_VT					9
#define LEVEL_GET_ACTIVE_USERS_VT						308
#define LEVEL_GET_HIT_RESULT_VT							319
#define LEVEL_GET_RUNTIME_ACTOR_LIST_VT					309
#define LEVEL_TICK_VT									109
#define LOCAL_PLAYER_RESET_ROT_VT						198 /* used in LocalPlayer::setRot */
#define LOCAL_PLAYER_SWING_VT							115
#define LOOPBACK_PACKET_SENDER_SEND_VT					3
#define MINECRAFT_GAME_ON_APP_RESUMED_VT				280
#define MINECRAFT_GAME_UPDATE_VT						3
#define MINECRAFT_SCREEN_CONTROLLER_TRY_EXIT_VT			13
#define PACKET_GET_ID_VT								2
#define PACKET_GET_NAME_VT								3
#define PACKET_HANDLER_DISPATCHER_INSTANCE_HANDLE_VT	2

// Offsets
#define ACTOR_ACTOR_COLLISION_OFF							0x8
#define ACTOR_BUILT_IN_ACTOR_COMPONENTS_OFF					0x260
#define ACTOR_FIRST_SYNCHED_ACTOR_DATA_ENTITY_WRAPPER_OFF	0x8		/* for Actor::getStatusFlag, Actor::setStatusFlag */
#define ACTOR_SECOND_SYNCHED_ACTOR_DATA_ENTITY_WRAPPER_OFF	0x178	/* for Actor::getNameTag */
#define APP_PLATFORM_MAIN_ACTIVITY_OFF						0x520
#define BLOCK_BLOCK_LEGACY_OFF								0x28
#define BLOCK_LEGACY_MATERIAL_OFF							0x100
#define CLIENT_INSTANCE_MINECRAFT_OFF						0xB0
#define CLIENT_INSTANCE_MINECRAFT_GAME_OFF					0xA8
#define CLIENT_INSTANCE_PACKET_SENDER_OFF					0xD0
#define DIMENSION_BLOCK_SOURCE_FROM_MAIN_CHUNK_SOURCE_OFF	0xB0
#define ITEM_ID_OFF											0x82
#define ITEM_MAX_USE_DURATION_OFF							0x10C
#define ITEM_STACK_BASE_BLOCK_OFF							0x18
#define ITEM_STACK_BASE_ITEM_REGISTRY_REF_OFF				0x8
#define LEVEL_RENDERER_PLAYER_MCE_CAMERA_OFF				0x778
#define MCE_CAMERA_VIEW_MATRIX_OFF							0xD8
#define MOVE_INPUT_HANDLER_JUMP_DOWN_OFF					0x6
#define PLAYER_GAME_MODE_OFF								0xA68
#define PLAYER_PLAYER_INVENTORY_OFF							0x5E0
#define SOME_SHIT_THAT_CONTAINS_APP_PLATFORM_OFF			0xE8A2170